### ISSUE TITLE
Confusing behaviour when using delegate proxy forwarding

### ISSUE THREAD

**Issue by sveinhal** [DeclarativeHub/Bond#311]
When using a collection view, one might be tempted to use 

``` swift
self.viewModel.items.bind(to: self.collectionView) { source, index, collectionView in
  let viewModel = source[index]
  let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "Cell", for: indexPath) as! Cell
  cell.viewModel = viewModel
  return cell
}
```

However, this does not give support for section headers. Currently the `CollectionViewBond` protocol does not support anything but cells. However, one can always set the `collectionView.bnd_dataSource.forwardTo` property.

However, when doing a partial implementation of the `UICollectionDataSource` protocol the compiler starts yelling at you. Leaving the protocol conformance undeclared works for _some_ of the protocol methods. 

This `ProtocolProxy.swift` implementation of `responds(to:)` returns **true** for `@selector(collectionView:layout:referenceSizeForHeaderInSection:)`, but **false** for `@selector(collectionView:viewForSupplementaryElementOfKind:atIndexPath:)` if you use the normal Swift names for those methods.

The solution is to explicitly declare your methods with the expected `@objc` annotation, like so:

``` swift
@objc(collectionView:viewForSupplementaryElementOfKind:atIndexPath:)
func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
    // ....
}
```

While this isn't exactly a bug per se, I think it is confusing enough to either warrant mention in the docs, or to extend `CollectionViewBond` to support supplementary views.

**Comment by srdanrasic** [comment]
Thanks for pointing this out @sveinhal! The docs should be improved.

**Comment by svachmic** [comment]
Hi there,

I'm trying to implement section headers somewhat along the lines @sveinhal outlined, but I seem to be getting a lot of errors, notably **Ambiguous reference to member 'collectionView'**.

I've tried the feed option and came up with this:
```
collectionView?.bnd_dataSource.feed(
            property: self.viewModel.contents,
            to: #selector(UICollectionViewDataSource.collectionView(_:viewForSupplementaryElementOfKind:at:)),
            map: {
                (value: Observable2DArraySection, col: UICollectionView, kind: String, indexPath: IndexPath) -> UICollectionReusableView
                
                let headerView = col.dequeueReusableSupplementaryView(ofKind: UICollectionElementKindSectionHeader, withReuseIdentifier:"iconHeaderCell", for: indexPath)
                
                headerView.backgroundColor = .yellow
                return headerView
        })
```
with no luck - am I getting closer?
Cheers

**Comment by srdanrasic** [comment]
I'm not sure why are you getting that error, but a simpler way to achieve that would be to implement method `collectionView(_:viewForSupplementaryElementOfKind:at:)` and then set `bnd_dataSource.forwardTo` to `self` (or to whom ever is implementing the method).

**Comment by svachmic** [comment]
@srdanrasic yes, I've tried that too - that works. But not in combination with `self.viewModel.contents.bind(to: self.collectionView!, using: MyBond())` - when I add `self.collectionView?.bnd_dataSource.forwardTo = self`, the first statement stops working for some reason...

**Comment by sveinhal** [comment]
You need to implement it like this:

```swift
@objc(collectionView:viewForSupplementaryElementOfKind:atIndexPath:)
func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
    // ....
}
```

**Comment by svachmic** [comment]
@sveinhal alright so I actually ran into an interesting problem. I did it the way you described and I wouldn't get it to work. I couldn't figure out what it was and then I "externalized the method into a separate object, which made it to work. When I implemented the method as you said (with the @objc) within UICollectionViewController it wouldn't work. I guess there is some internal machinery within UIKit that prevents this from happening. Anyway - I got it to work, in case somebody else will try to solve the same issue, hopefully our discussion will be of any help. Thanks a lot again to both of you.

**Comment by srdanrasic** [comment]
Bond 7 favours binder data source subclassing instead of protocol proxies. https://github.com/DeclarativeHub/Bond/blob/master/Documentation/DataSourceSignals.md#advanced-bindings-custom-binder-data-sources

**Comment by diriarte2111** [comment]
> @sveinhal alright so I actually ran into an interesting problem. I did it the way you described and I wouldn't get it to work. I couldn't figure out what it was and then I "externalized" the method into a separate object (NSObject to be assigned to the forwarding), which made it to work.
> 
> When I implemented the method as you said (with the `@objc`) within `UICollectionViewController` it wouldn't work. I guess there is some internal machinery within UIKit that prevents this from working. Anyway - I got it to work, in case somebody else will try to solve the same issue, hopefully our discussion will be of any help. Thanks a lot again to both of you.

What was the final solution for this?facing this problem now!!!

**Comment by svachmic** [comment]
> > @sveinhal alright so I actually ran into an interesting problem. I did it the way you described and I wouldn't get it to work. I couldn't figure out what it was and then I "externalized" the method into a separate object (NSObject to be assigned to the forwarding), which made it to work.
> > When I implemented the method as you said (with the `@objc`) within `UICollectionViewController` it wouldn't work. I guess there is some internal machinery within UIKit that prevents this from working. Anyway - I got it to work, in case somebody else will try to solve the same issue, hopefully our discussion will be of any help. Thanks a lot again to both of you.
> 
> What was the final solution for this?facing this problem now, if hay forward the dataSource de binding stop working and everything works as I normally use without binding.

Hey there, it's been a while and honestly, I haven't worked on the project where I implmented this for a year or so. But the solution from the time we had this discussion is here:

https://github.com/svachmic/ios-url-remote/blob/master/URLRemote/Classes/Controllers/ActionsCollectionViewController.swift

But again - it's a bit outdated.
