### ISSUE TITLE
Sort MutableObservableArray<Item>

### ISSUE THREAD

**Issue by iandundas** [DeclarativeHub/Bond#376]
In ReactiveKit 2 there was the rather magical ability to sort a `CollectionProperty<[Item]>`'s events in-flight, as in:

```swift

let collection: CollectionProperty<[Item]>

let sorted: Stream<CollectionChangeset<[Item]>> = collection.sort { (a: Item, b:Item) -> Bool in 
    return a.whatever > b.whatever
}
```

Similar to #335, could it be possible to add this to the roadmap for Bond (6?), to port this functionality over to the new `MutableObservableArray` type?

Cheers!

**Comment by iandundas** [comment]
The hard bit is mapping the `ObservableArrayChange`:

```swift
let sorted = collection.map { (event: ObservableArrayEvent<String>) -> ObservableArrayEvent<String> in
  
    event.dataSource.sorted(by: (String, String) -> Bool) // easy to sort

    // The hard bit: 
    switch event.change{
    case .inserts([Int]):break;
    case .deletes([Int]):break;
    case .move(Int, Int):break;
    case .updates([Int]): break;
    } 
  }
```

Taking a look at the algorithm used in ReactiveKit 2 to see if I can do it

**Comment by iandundas** [comment]
Here's my rather naïve implementation:


```swift
extension MutableObservableArray where Item: Comparable {
  
  public func sorted(by sorter: @escaping (Item, Item) -> Bool) -> Signal<ObservableArrayEvent<Item>, NoError>{
    return Signal { (observer: AtomicObserver<ObservableArrayEvent<Item>, NoError>) -> Disposable in
      
      let disposable = DisposeBag()
      var differ: MutableObservableArray<Item>! // Stores a sorted version of the datasource, generates diff events
      
      self.observeNext(with: { (latestUpdate: ObservableArrayEvent<Item>) in
        let sorted = latestUpdate.dataSource.array.sorted(by: sorter)
        
        if differ == nil {
          differ = MutableObservableArray<Item>(latestUpdate.dataSource.array)
          differ
            // we don't want to pass on the first .reset event containing the unsorted array
            .skip(first: 1)
            // pass events from the differ to the signal observer:
            .observeNext(with: observer.next).dispose(in: disposable)
          
          // create our own .reset event instead, with the sorted array:
          observer.next(ObservableArrayEvent(change: .reset, source: sorted))
        }
        else {
          guard let differ = differ else {return}
          
          // Replace contents of differ to generate diff event for observer:
          differ.replace(with: sorted, performDiff: true)
        }
      }).dispose(in: disposable)
      
      return disposable
    }
  }
}

```

**Usage:**

```swift
let collection = MutableObservableArray<Int>([])

let sorted: Signal<ObservableArrayEvent<Int>, NoError> = collection.sorted { (a, b) -> Bool in
    return a < b
}

sorted.observeNext { (event: ObservableArrayEvent<Int>) in
    print("Received: \(event.change), array: \(event.dataSource.array)")

    switch event.change {
        case .reset: fallthrough
        case .endBatchEditing: print("")
        default: break
    }
}

collection.append(10)
collection.append(3)
collection.append(2)
collection.append(1)
collection.moveItem(from: 0, to: 2)
```

outputs: 

	Received: reset, array: []

	Received: beginBatchEditing, array: []
	Received: inserts([0]), array: [10]
	Received: endBatchEditing, array: [10]

	Received: beginBatchEditing, array: [10]
	Received: inserts([0]), array: [3, 10]
	Received: endBatchEditing, array: [3, 10]

	Received: beginBatchEditing, array: [3, 10]
	Received: inserts([0]), array: [2, 3, 10]
	Received: endBatchEditing, array: [2, 3, 10]

	Received: beginBatchEditing, array: [2, 3, 10]
	Received: inserts([0]), array: [1, 2, 3, 10]
	Received: endBatchEditing, array: [1, 2, 3, 10]

	Received: beginBatchEditing, array: [1, 2, 3, 10]
	Received: endBatchEditing, array: [1, 2, 3, 10]

Whereas the output if observing the collection (unsorted) directly is: 

	Received: reset, array: []

	Received: inserts([0]), array: [10]
	Received: inserts([1]), array: [10, 3]
	Received: inserts([2]), array: [10, 3, 2]
	Received: inserts([3]), array: [10, 3, 2, 1]
	Received: move(0, 2), array: [3, 2, 10, 1]


So the difference is an overuse of the begin/endBatchEditing, but I can't see that doing much harm. In terms of performance it's probably not ideal I guess.

Would you be interested in me submitting a pull request for this with tests, or is there another implementation path that could be better?

**Comment by iandundas** [comment]
*updated the above to make examples better*

**Comment by srdanrasic** [comment]
I'll need few days to think about this :) I agree though, it would be nice to see sorting again.

**Comment by iandundas** [comment]
Cool 👍🏻

**Comment by iandundas** [comment]
Hey - did you have further ideas on this one?

**Comment by srdanrasic** [comment]
Hi @iandundas, I didn't get much time to work on this recently. I want to do it but not sure when I'll get time. We would need a bit more performant implementation.

**Comment by slavikus** [comment]
I'll watch this ticket as I'd love to see sortable arrays as well :)

**Comment by iandundas** [comment]
hey no worries :) fingers crossed

**Comment by rslim087g** [comment]
Are there any updates on this? It seems like a very useful feature!

**Comment by rslim087g** [comment]
It looks like the sorted operator doesn't work unless I add the extension @iandundas provided. 
   
private func setupCellConfiguration() {

        self.Chats.sorted(by: { (l, r) -> Bool in
            return l.lastMessage < r.lastMessage
        })
        self.Chats.filter({ (chat) -> Bool in
                return chat.lastMessage != 1
        })
        
        .bind(to: tableview) { Chats, IndexPath, tableview in
        let cell = tableview.dequeueReusableCell(withIdentifier: "cell")
        cell?.textLabel?.text = "\(Chats[IndexPath.row].lastMessage)"
        return cell!
        }
        
        
    }

**Comment by slavikus** [comment]
@srdanrasic @tonyarnold your magic is needed! :))

**Comment by srdanrasic** [comment]
Sorting is back!

**Comment by iandundas** [comment]
<img src=https://dsc.cloud/iandundas/cglt.jpg />
