### ISSUE TITLE
Feature Request - Binding to NSTableView with section support

### ISSUE THREAD

**Issue by Joebayld** [DeclarativeHub/Bond#423]
Hi all. I am looking to add the support so I can bind to a NSTableView with multiple columns. I see the it's not supported yet. Any insight on why this hasn't been added yet? I can start the work on adding it, just want to know what I'm getting into.. 

thanks

**Comment by tonyarnold** [comment]
It hasn't been added because nobody has needed it yet. PRs are very welcome 😀
