### ISSUE TITLE
Docs - Example for NSTableView

### ISSUE THREAD

**Issue by gm2211** [DeclarativeHub/Bond#438]
BLUF: How do you bind an array to a `NSTableView`

It looks like all code samples in the docs are for UIKit (e.g. UITableView), but I couldn't find any for AppKit.

NSTableView seems to be quite different from UITableView.

The `README.md` shows how to bind an array to a UITableView by creating and returning a new cell every time a new element is added to the array, this does not seem to work for `NSTableView` (no `dequeueCellForReuse`).

 By reading a bit about `NSTableView`, I found that it works with a datasource you set on it and I found a reactive proxy binding in the source of Bond, but I can't quite figure out how to piece this all together effectively.

Hence my question: what are the best practices around binding an array to a `NSTableView` so that it displays the contents of the array as rows?

**Comment by kaishin** [comment]
I am in a similar situation. I made it to work in 6, but I am struggling a bit to do so with my view-based NSTableView in 7-beta. Specifically, I am not sure what's the rationale behind the changes and the recommended way of using `TableViewBinderDataSource` (subclassing, extending, etc). I'd be happy to open PRs and add missing functionality, but I can't do so without more understanding of the reason behind these changes in 7.

**Comment by srdanrasic** [comment]
We have some playgrounds since v7.
