### ISSUE TITLE
Extending ObservableArray

### ISSUE THREAD

**Issue by killev** [DeclarativeHub/Bond#493]
Hi there,

Have been using Bond for many projects. Thanks for the effort and time you've put into it.

An idea that NSFetchedResultController can be treated as ObservableArray has bothered me for a long time, so I started implementing it in code.

What I found digging into this problem:

1. ObservableArray events aren't thread-safe:

```swift
public protocol ObservableArrayEventProtocol {
    associatedtype Item
    var change: ObservableArrayChange { get }
    var source: ObservableArray<Item> { get }
}
```
Then you populate the event togather with array change:
```swift
public func moveItem(from fromIndex: Int, to toIndex: Int) {
        lock.lock(); defer { lock.unlock() }
        let item = array.remove(at: fromIndex)
        array.insert(item, at: toIndex)
        subject.next(ObservableArrayEvent(change: .move(fromIndex, toIndex), source: self))
}
```

When you change and observe array in different contexts (main and background f.e.) the situation when change array several times before you the first observe is invoked is possible. Therefore you can't send *self* on *source* as it contains a new array. 

```swift
subject.next(ObservableArrayEvent(change: .move(fromIndex, toIndex), source: self))
```

Below the test that clearly demonstrates the issue:

```swift
 func testAsync() {
        let async = self.expectation(description: "async")
        
        let array = MutableObservableArray<Int>([])
        var expected:[Int] = []
        
        let disposable = array.observeIn(.immediateOnMain).observeNext{ event in
            XCTAssertEqual(expected, event.source.array)// we always should have one more element every interation, but most probably we have all 10 elements here
            expected.append(expected.count)
            Thread.sleep(forTimeInterval: 0.01) //Here we need to wait a bit in order to disasync with background
            if expected.count == 10 {
                async.fulfill()
            }
        }
        
        DispatchQueue.global().async {
            for i in 0..<10 {
                array.append(i)
            }
        }
        wait(for: [async], timeout: 1)
        disposable.dispose()
    }
```
And, of course, this breaks logic of binding to TableView and CollectionView.
I would suggest sending the copy of array relevant for every event.

```swift
public protocol ObservableArrayEventProtocol {
    associatedtype Item
    var change: ObservableArrayChange { get }
    var source: [Item] { get }
}
```

Then populate the event with current state of data. So the receiver always gets array relevant to the change:

```swift
public func moveItem(from fromIndex: Int, to toIndex: Int) {
        lock.lock(); defer { lock.unlock() }
        let item = array.remove(at: fromIndex)
        array.insert(item, at: toIndex)
        subject.next(ObservableArrayEvent(change: .move(fromIndex, toIndex), source: array))
}
```

**Comment by killev** [comment]
The second I clarified is that we have no any public/open abstractions under ObservableArray. So it's not expandable by the 3d party libraries.

I forked the Bond and did the following.

1. Split ObsevableArray into 2 classes:
- open ObservableArrayBase. Align all external functiality to it (maps, bindings etc.).
- public ObservableArray derived from ObservableArrayBase
4. Converted *array* into propery so that inherited classes can provide their own implementation
5. Changed  source to Array<Item> in order to prevent race condition
6. Other minor changes.

You can find the changes here:
https://github.com/killev/Bond/commits/master

**Comment by tonyarnold** [comment]
I think I've been looking for something like this - @srdanrasic what are your thoughts on tidying this up and making a PR?

**Comment by killev** [comment]
@tonyarnold @srdanrasic Let's split them into 2 different issues and discuss them separately. I have some arguments for both of them.

BTW. And if we clarify the architecture I would be pleased to implement it on my own.

**Comment by killev** [comment]
So discussing extensibility here.

I've just realized what is the purpose of **DataSourceEventProtocol**  😄
From this point of view, the solution suggested by @srdanrasic seems to be more preferable. 

On the other hand, we have a bunch of useful functionality already bound to **ObservableArrayEventProtocol** like *map*, *filter*.

Also, having the class **ObservableArray** in

```swift
public protocol ObservableArrayEventProtocol {
    associatedtype Item
    var change: ObservableArrayChange { get }
    var source: ObservableArray<Item> { get }
}
```

prevents us from using ** ObservableArrayEventProtocol** as events for other classes. Only inheritance is supported.

**Comment by tonyarnold** [comment]
Yeah, I'm following along with @killev here. My use case right now is as follows:

I have a framework that exposes an Objective-C wrapper that sits around a C++ "core". This exposes an underlying C++ list that for all intents and purposes _looks_ like an `NSMutableArray`. 

In order to make changes, or to read changes, they _must_ go back through the C++ list (via the ObjC API).

What I'm trying to do is wrap an `ObservableCollection` (inspired by `ObservableArray`) around this so that I change the `ObservableCollection` instance, and it directly updates the underlying instance (versus what `ObservableArray` does now, which is takes a copy of the array used to initialise the instance).

Does that make sense? Having support via a standard `ObservableSequenceEventProtocol` or `ObservableCollectionEventProtocol` would make my life a lot easier.

**Comment by srdanrasic** [comment]
I like the idea of `ObservableCollection` that wraps anything conforming to `Swift.Collection` protocol. We had something like that in an early version of Bond, but `Swift.Collection` was a mess back then and working with it involved a lot of generic constraints that would crash Xcode all the time. 

I guess `ObservableCollection` could be defined as:

```swift
class ObservableCollection<UnderlyingCollection: Collection> {}
```

With a mutable variant:

```swift
class MutableObservableCollection<UnderlyingCollection: MutableCollection>: ObservableCollection<UnderlyingCollection> {}
```

Its event could be defined as

```swift
public protocol ObservableArrayEventProtocol {
    associatedtype Item
    associatedtype UnderlyingCollection: Collection
    var change: ObservableArrayChange { get }
    var source: UnderlyingCollection { get }
}
```

To be consistent with changes proposed in #512. 

I really like this idea. It could replace all existing observable collections if done properly.

**Comment by tonyarnold** [comment]
I’ll take a swing at this - I’d mostly ended up on this in my own work - I just need to re-implement the diffing.

**Comment by tonyarnold** [comment]
OK, there's some initial work in #513 to expose a more extensible `ObservableCollection` - I need to:

- Write some tests
- Flesh out some documentation on how to extend
- Deprecate/typealias ObservableArray to this new class

**Comment by srdanrasic** [comment]
`ObservableCollection` and `MutableObservableCollection` are now available in Bond 7. Check out the accompanying playgrounds.
