### ISSUE TITLE
Custom header view

### ISSUE THREAD

**Issue by IvoPintodaSilva** [DeclarativeHub/Bond#503]
I am using Bond to configure a UITableView with several sections and I want to have custom headers for each section.

I did the following:

1. I forwarded the delegate events to my UITableViewDelegate
`tableView.reactive.delegate.forwardTo = self`

2. Implemented viewForHeaderInSection in order to dequeue the desired header.

Perfect until now. However, when I run the app, the title from my custom cell is overlapped with the title from the TableViewBond.

How about a "viewForHeader" method instead of a "titleForHeader" in the TableViewBond?

Cheers! 🍻

**Comment by srdanrasic** [comment]
Hmm, could it be that you have some layout issues? Bond should not affect layout of table view cells and views so I'm not sure what could be the reason for the overlap.

**Comment by srdanrasic** [comment]
Check out last two section of https://github.com/DeclarativeHub/Bond/blob/master/Documentation/DataSourceSignals.md on two possible ways to implement that.

**Comment by PKCoder2020** [comment]
`viewForHeaderInSection` is a delegate method of UITableView. I don't think Bond has support for this delegate method. Any idea, how to implement this?
