### ISSUE TITLE
Feature Request : Implement ObservableSetEventProtocol to provide a "bind(to: )" method for MutableObservableSet

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/Bond#504]
Currently [`MutableObservableArray`](https://github.com/ReactiveKit/Bond/blob/0e6e960df2ebd8431eb472a65f1a2b9ccd1867fb/Sources/Bond/Collections/ObservableArray.swift#L146) can be bound to a tableView because it conforms to [`ObservableArrayEventProtocol`](https://github.com/ReactiveKit/Bond/blob/0e6e960df2ebd8431eb472a65f1a2b9ccd1867fb/Sources/Bond/Collections/ObservableArray.swift#L39) via the [`SignalProtocol`](https://github.com/ReactiveKit/Bond/blob/0e6e960df2ebd8431eb472a65f1a2b9ccd1867fb/Sources/Bond/AppKit/NSTableView.swift#L214) extension.

But this is currently the only datasource that seems to implement that. `MutableObservableSet` should provide the same functionality so that it can be bound to a tableView with `bind(to: )` -- the same could be said for an observable Dictionary as well.

**Comment by srdanrasic** [comment]
`ObservableSet` conforms to `SignalProtocol` with elements of type `ObservableSetEvent`. Table and collection view bindings work only with `ObservabeArrayEvent`.

What would be required here is to implement an operator that maps `ObservableSetEvent` into `ObservabeArrayEvent`. It would probably be a `sort` operator that sorts the set elements into an array. 

Set has elements in an undefined order. When a new element is added, to order is usually completely shuffled so bindings would only make sense if there were some kind of a `sort` operator on set. 

Same applies for `ObservableDictionary`.

This is not a trivial work and I do not have the time to implement that, but I'll leave the ticket open as a possible future enhancement.

**Comment by srdanrasic** [comment]
Bond 7 introduces `sortedCollection` operator on `ObservableSet` and `ObservableDictionary` which enables their binding to table or collection views.
