### ISSUE TITLE
UITableView Controlling Animations and scrollview offset 

### ISSUE THREAD

**Issue by joergbirkhold** [DeclarativeHub/Bond#508]
Hi there

I am using a MutableObservableArray as Backing for my TableView. Everything fine s far, from time to time a pull new Data from the sever using replace like here:
```swift
numbers.replace(with: [0, 1, 3, 4], performDiff: true)
```
Right now it works but I am not really satisfied with how it looks. After the update there are 2 possible cases
1. Only a update of the cell content ist required, how can I control the animation here?
2. New cells are inserted, but I want to keep my scrollposition, what ist the best way to achieve that?

Thanks for any help and hints

**Comment by srdanrasic** [comment]
Hi @joergbirkhold,

I have just released v3.7.0 with better support for table view animations customizations. Check the [updated documentation](https://github.com/DeclarativeHub/Bond/blob/master/Documentation/DataSourceSignals.md).

As for the scroll position, that is a problem with UITableView and not related to Bond. Try googling for "uitableview keep scroll position". You could subclass UITableView and override methods like `insertRows(at:with:)` and adjust the scroll position there.

Check out [this](https://github.com/DeclarativeHub/Bond/blob/master/Sources/Bond/UIKit/UITableView.swift#L83) to see how Bond applies events to the table view. You could also implement a custom TableViewBinder and apply them yourself, but not sure if that would help.
