### ISSUE TITLE
SIGABRT : Could not cast value of type 'NSNumber' (...) to '__C.UITableViewCellEditingStyle' (...).

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/Bond#509]
# Environment
Xcode : 9.2
Cocoapods : 

- Using Bond (6.6.1)
- Using Differ (1.0.3)
- Using ReactiveKit (3.9.1)

# Description
Using MutableObservableArray bound to a UITableView I am able to populate a table view with 2 predefined users (great !). I am now trying to enable the swiping effect to be able to delete a cell from the table (see attached picture).

<img width="259" alt="screen shot 2018-03-23 at 8 11 18 am" src="https://user-images.githubusercontent.com/3268395/37830976-e7355ca2-2e71-11e8-9e0e-807c260eaa4c.png">

I was able to do that by using the following : 
```
extension UITableView {
    var selectedRow: Signal<Int, NoError> {
        return reactive.delegate.signal(for: #selector(UITableViewDelegate.tableView(_:didSelectRowAt:))) {
            (subject: SafePublishSubject<Int>, _: UITableView, indexPath: IndexPath) in
            subject.next(indexPath.row)
        }
    }
    var commitStyle: Signal<Void, NoError> {
        return reactive.dataSource.signal(for: #selector(UITableViewDataSource.tableView(_:commit:forRowAt:))) {
            (subject: SafePublishSubject<Void>, tv: UITableView, editingStyle: UITableViewCellEditingStyle, indexPath: IndexPath) in
            switch editingStyle {
            case .delete: tv.deleteRows(at: [indexPath], with: .automatic)
            default:  print("Hmmm, not sure about that one.")
            }
            subject.next()
        }
    }
}
```

The first member of the extension `selectedRow` is taken straight from the docs. I added the second member `commitStyle` so the UITableView would know that [tableView(_:commit:forRowAt:)](https://developer.apple.com/documentation/uikit/uitableviewdatasource/1614871-tableview) is implemented by the dataSource, since per the UIKit doc : 

> To enable the swipe-to-delete feature of table views (wherein a user swipes horizontally across a row to display a Delete button), you must implement this method.

_Disclaimer : I might not be using the proper way to implement additional data source functionality. So if that's the case, please let me know how to do that !_

# Problem

When I press the red **Delete** button in the cell, I get the following error : 

> Could not cast value of type 'NSNumber' (0x1065f92e8) to '__C.UITableViewCellEditingStyle' (0x102be96e0).
> 2018-03-23 08:21:50.722806-0500 FrameWork101[68787:5053599] Could not cast value of type 'NSNumber' (0x1065f92e8) to '__C.UITableViewCellEditingStyle' (0x102be96e0).

And this is what Xcode is showing in the Debug window : 

![screen shot 2018-03-23 at 8 23 20 am](https://user-images.githubusercontent.com/3268395/37831445-8342c9f8-2e73-11e8-9166-a32c5eee8e17.png)

Is this an issue with how I am choosing to implement some of the data source protocol functionality or an actual bug ?

Thanks !

**Comment by srdanrasic** [comment]
Yes, you are right, there are issues UITableViewCellEditingStyle, more specifically, there are issues with ObjC enums. I'm not sure of a way to support that. 

What you can do is declare the parameter as `NSNumber` or `Int` and then instantiate `UITableViewCellEditingStyle` from raw value (the number).

**Comment by srdanrasic** [comment]
I have updated the documentation with this so I'll close the ticket:
https://github.com/DeclarativeHub/Bond/blob/master/Documentation/ProtocolProxies.md#important-argument-types

**Comment by npvisual** [comment]
Ok. Thanks for the pointer. I tested it this morning and it works fine : 

```
    // Swipe-to-delete feature
    var commitStyle: Signal<(Int, Int), NoError> {
        return reactive.dataSource.signal(for: #selector(UITableViewDataSource.tableView(_:commit:forRowAt:))) {
            (subject: SafePublishSubject<(Int, Int)>, tv: UITableView, editingStyle: Int, indexPath: IndexPath) in
            subject.next((editingStyle,indexPath.row))
        }
    }

```

And then to observe the signal : 

```
        controller.tableView.commitStyle.observeNext { (editingStyle,row) in
            switch editingStyle {
            case 1: service.family.remove(at: row)
            default:  print("Hmmm, not sure about that one.")
            }
        }.dispose(in: controller.bag)
```
