### ISSUE TITLE
Moving an observable array item to the end of the array?

### ISSUE THREAD

**Issue by tonyarnold** [DeclarativeHub/Bond#510]
https://github.com/DeclarativeHub/Bond/blob/a90d5c6fdbeb35fc1c380301e945df5fd846f183/Sources/Bond/Collections/ObservableArray.swift#L173

I wonder if this should be:

```diff
- array.insert(item, at: toIndex)
+ if toIndex == array.count + 1 {
+          array.append(item)
+ } else {
+          array.insert(item, at: toIndex)
+ }
```

As it looks right now, the only way to move an item to the end of the array is to do a delete then append. 

Am I wrong? Is this worth changing?

**Comment by srdanrasic** [comment]
I think you are right. This should be able to move an item to the end.

**Comment by srdanrasic** [comment]
Hmm, I was about to change this, but `array.count + 1` is not the end of the array. The end is at `array.count` and `array.insert(item, at: toIndex)` when `toIndex == array.count` works. 

Are you sure that we have a problem here?

**Comment by tonyarnold** [comment]
This is confusing the hell out of me: and I think it's how macOS handles drag and drop in tables.

Basically it allows dragging between existing indexes, however it works like this:

```
Position 0
Item 1
Position 1
Item 2
Position 2
Item 3
Position 3
```

I've probably got some logic in my app that's countering that. I will dig deeper.

**Comment by tonyarnold** [comment]
Yeah, this is absolutely a misunderstanding on my end. Thanks for taking some time to work through it with me!
