### ISSUE TITLE
Improve thread safety of Observable Collections

### ISSUE THREAD

**Issue by srdanrasic** [DeclarativeHub/Bond#512]
Observable collections are not thread safe as is detailed in #493. 

There are two suggested approaches to solving this.

1. Change observable array event source type:

```swift
public protocol ObservableArrayEventProtocol {
    associatedtype Item
    var change: ObservableArrayChange { get }
    var source: [Item] { get } // <- this is changed from ObservableArray
}
```

This would be a source breaking change, but I don't think many people rely on the `source` type being ObservableArray.

2. Change the implementation of the ObservableArrayEvent initializer in a way that it makes a copy of the source array.

```swift
public struct ObservableArrayEvent<Item>: ObservableArrayEventProtocol {
    ...
    public init(change: ObservableArrayChange, source: ObservableArray<Item>) {
        self.change = change
        self.source = ObservableArray(source.array) // <- change from `self.source = source`
    }
    ...
}
```

This would ensure that each event has a thread safe copy without any API changes. It's also a very simple change. 

Initially I was in favour of suggestion #1, but we also have to think of other collections and make the same change for all of them. In that case the second approach seems like a better solution, especially when taking Observable2DArray into account.

@killev @tonyarnold

**Comment by killev** [comment]
@srdanrasic @tonyarnold 

Let's think of this from another point of view: Is it really correct to send a source (producers) of change as a part of payload? In this case Properties (which may be treated as a common case of ObservableArray) also should send themselves instead of the value.

Then.

Having a source in observation block propagates to use it as Signal. For example, it becomes possible to subscribe to it (senseless especially, if it's always a new copy of the source, like you're suggesting), or (in some cases) even perform **next** (it's even more dangerous as brakes locking!!).

 In observation logic, you need just an immutable data, not a source.

As to supporting other collections.
They all consist of some data inside of them.

```swift
public class Observable2DArray<SectionMetadata, Item>: SignalProtocol {

    public fileprivate(set) var sections: [Observable2DArraySection<SectionMetadata, Item>]
```

And this data just should implement DataSourceProtocol to be easily used in bindings. So we shouldn't break a lot.

**Comment by killev** [comment]
Moreover.

> This would be a source breaking change, but I don't think many people rely on the source type being ObservableArray.

According to above, this change:
```swift
public struct ObservableArrayEvent<Item>: ObservableArrayEventProtocol {
    ...
    public init(change: ObservableArrayChange, source: ObservableArray<Item>) {
        self.change = change
        self.source = ObservableArray(source.array) // <- change from `self.source = source`
    }
    ...
}
```
is even more dangarous as those people who rely on source being ObservableArray won't get the original instance anymore.

**Comment by srdanrasic** [comment]
Good arguments. ObservableArray is supposed to have something like value semantics - it cannot be mutated from the outside - as opposed to MutableObservableArray which can be mutated by the user. 

The ability to subscribe to the ObservableArray from the event is a problem though. You are right, it should not even be allowed.

Let's change the events to send the underlying collection instead. Although it's a breaking change, it should be a minor one.

Would you like to make a PR?

**Comment by killev** [comment]
Ok. I'll make it over the weekend.

**Comment by srdanrasic** [comment]
Cool, no rush.

**Comment by killev** [comment]
@tonyarnold @srdanrasic Correct me I'm wrong, but there's nothing to do anymore with this according to #513.

As long as you need any help - let me know. I have next several days free and!
BTW. If you need to something from me - reach me on skype: mw_peter, or let me know about any suitable channel for you (Slack, Viber, WhatsApp).

**Comment by tonyarnold** [comment]
@killev sorry, that's my fault. I had an in-progress version of what was being discussed, so I thought tidying it up would save some time. 

I have yet to do the same for the 2D arrays, dictionaries or sets - but yeah, there's not a lot of work left in it.

**Comment by srdanrasic** [comment]
@killev, yeah, let's not do that since we are doing the collection.

**Comment by srdanrasic** [comment]
Implemented in Bond 7.
