### ISSUE TITLE
TableViewBond -> TableViewBinder

### ISSUE THREAD

**Issue by Maxatma** [DeclarativeHub/Bond#520]
Any TableViewBond to TableViewBinder migration guide?

I had this TableViewBond:
```
struct AttachmentsBond: TableViewBond {
    
    func cellForRow(at indexPath: IndexPath,
                    tableView: UITableView,
                    dataSource: Observable2DArray<String, AttachmentCellVM>) -> UITableViewCell {
        let cell       = tableView.dequeueReusableCell(withIdentifier: "AttachmentCell", for: indexPath) as! AttachmentCell
        cell.viewModel = dataSource[indexPath.section].items[indexPath.row]
        return cell
    }
    
    func titleForHeader(in section: Int, dataSource: Observable2DArray<String, AttachmentCellVM>) -> String? {
        return dataSource[section].metadata
    }
}

```

and bind it like this: 

`        vm.vms.bind(to: table, using: AttachmentsBond())
`

What should I do to migrate it to TableViewBinder?

I tried: 

```
final class AttachmentsBinder: TableViewBinder<Observable2DArray<String, AttachmentCellVM>> {
    
   override func cellForRow(at indexPath: IndexPath,
                    tableView: UITableView,
                    dataSource: Observable2DArray<String, AttachmentCellVM>) -> UITableViewCell {
        let cell       = tableView.dequeueReusableCell(withIdentifier: "AttachmentCell", for: indexPath) as! AttachmentCell
        cell.viewModel = dataSource[indexPath.section].items[indexPath.row]
        return cell
    }
    
    func titleForHeader(in section: Int, dataSource: Observable2DArray<String, AttachmentCellVM>) -> String? {
        return dataSource[section].metadata
    }
}

```

but in:

`        vm.vms.bind(to: table, using: AttachmentsBinder())
`

I have compiler error:
 `Extra argument 'using' in call`

**Comment by srdanrasic** [comment]
Hey @Maxatma, have you seen this: https://github.com/DeclarativeHub/Bond/blob/master/Documentation/DataSourceSignals.md#advanced-bindings-for-table-views ?

**Comment by Maxatma** [comment]
@srdanrasic Yes, sure. Still a bit complicated to understand what im doing wrong.
Should i init AttachmentsBinder with createCell ?

**Comment by srdanrasic** [comment]
Ah, yes, you should have inited it with createCell. I've just made a patch release 6.7.1 where that is not required so your code should work now if you update. Thank you for reporting this!

**Comment by Maxatma** [comment]
@srdanrasic Thanks!
How about header/footer implementation in `TableViewBinder`?
There is no analog for this function in `TableViewBinder`, as I can see :
  ```
  func titleForHeader(in section: Int, dataSource: Observable2DArray<String, AttachmentCellVM>) -> String? {
        return dataSource[section].metadata
    }
```
