### ISSUE TITLE
custom datasource compile error 

### ISSUE THREAD

**Issue by Maxatma** [DeclarativeHub/Bond#521]
```
class MyDataSource /* or: extension MyViewController */: UITableViewDataSource {

    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        fatalError("This will never be called.")
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        fatalError("This will never be called.")
    }

    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return "Title"
    }
}
```

This will not compile because of the reason:

` Type 'MyDataSource' does not conform to protocol 'NSObjectProtocol'`

**Comment by tonyarnold** [comment]
The easy answer is to make `MyDataSource` a subclass of `NSObject`. 

I’m not sure what this has to do with Bond, though?

**Comment by Maxatma** [comment]
I forgot to say, this is what u have in your [documentation](https://github.com/DeclarativeHub/Bond/blob/master/Documentation/DataSourceSignals.md#custom-data-source-in-addition-to-bindings).

**Comment by srdanrasic** [comment]
I would suggest checking out Bond 7 which favours default binder data source subclassing instead of using protocol proxies.
