### ISSUE TITLE
Swift 4.1 build Bond 6.8.0 failure

### ISSUE THREAD

**Issue by hrstruggle1** [DeclarativeHub/Bond#523]
Xcode 9.3 and Swift 4.1 

![image](https://user-images.githubusercontent.com/10215430/39081701-932ce8b4-4578-11e8-9595-836d3291493a.png)

```swift
internal extension BNDInvocation {

    func readArgument<T>(_ index: Int) -> T {
        let size = Int(methodSignature.getArgumentSize(at: UInt(index)))
        let alignment = Int(methodSignature.getArgumentAlignment(at: UInt(index)))

        let pointer = UnsafeMutableRawPointer.allocate(byteCount: size, alignment: alignment)
        getArgument(pointer, at: index)

        defer {
            pointer.deallocate()
        }

        let type = methodSignature.getArgumentType(at: UInt(index))
```

failure info : Cannot convert value of type 'UInt' to expected argument type 'Int'

**Comment by tonyarnold** [comment]
Sorry you're seeing this problem, I'd like to help but I need more information:

- When is this occurring? 
- How are you including Bond in your project?
- Can you verify that you have `SWIFT_VERSION = 4.0` (or 4.1) set in your project?

**Comment by hrstruggle1** [comment]
@tonyarnold  hi, thank U for your reply  : )
yes, i verify my project SWIFT_VERSION = 4.1, and use cocoapods 1.5.0 installation

**Comment by srdanrasic** [comment]
I'll close this since it's probably outdated now.
