### ISSUE TITLE
UITableView bind to custom xib UITableViewCell

### ISSUE THREAD

**Issue by noaraz** [DeclarativeHub/Bond#530]
Hi,
I'm using bond v6.8.2 and I'm trying to bind my table view with 
**bind(to: collectionView, cellType: UserCell.self) {...}**

my problem is that your implementation does not support custom UITableViewCell with xib file.
if i change the bind function code to: 
**tableView.register(UINib(nibName: identifier, bundle: nil), forCellReuseIdentifier: identifier)**
instead of:
**tableView.register(cellType as AnyClass, forCellReuseIdentifier: identifier)**

it works.

Any chance new version with this option is available?

Thank you,
Noa

**Comment by noaraz** [comment]
Are there any news about the subject?

**Comment by jsembdner** [comment]
[This](https://github.com/DeclarativeHub/Bond/issues/592) seems to be another linked issue to this.

**Comment by srdanrasic** [comment]
We support this now.
