### ISSUE TITLE
Use Bond in Obj-C

### ISSUE THREAD

**Issue by olbrichj** [DeclarativeHub/Bond#532]
We have a huge codebase based on Obj-C and are trying to switch at least for the UI to Swift. Sadly our viewmodel can't be moved to Swift. Is there an option to create Observables in Obj-C? Bindings would be done in the Swift part.

Thanks

**Comment by Maxatma** [comment]
If u gonna rewrite some vms to use Bond, why cant u rewrite it using Swift?

**Comment by olbrichj** [comment]
We're using a lot of C++. So no way around Obj-C

**Comment by tonyarnold** [comment]
There’s no option for this currently. I currently work on a project that’s a mix of C++ and Objective-C/Swift, and we took a slightly different approach: the C++ components are all pulled out into a separate framework that exposes an Objective-C API. This way, all of the application code can remain in Swift. 

That may not be suitable for your purposes and your situation, but it has been working really well (and means I get to use Bond for UI components).
