### ISSUE TITLE
Confusing error while set the keyPath for the ProtocolProxy

### ISSUE THREAD

**Issue by luziqin** [DeclarativeHub/Bond#533]
Here is my code:
![screen shot 2018-06-01 at 2 56 16 pm](https://user-images.githubusercontent.com/3337474/40826042-002da450-65ac-11e8-9131-d4983a95bfb4.png)

It is totally as same as the example in documentation, but i got this error

>  Incorrect argument label in call (have 'for:keyPath:', expected 'for:selector:')

Can any body help?

**Comment by tonyarnold** [comment]
Hi @luziqin - did you manage to sort this issue out?
