### ISSUE TITLE
Cannot bind a subclass of UITableViewDataSource

### ISSUE THREAD

**Issue by eduardbosch** [DeclarativeHub/Bond#534]
Hi,

I'm trying to use a subclass of UITableViewDataSource so I could use the `SkeletonTableViewDataSource` that inherits from `UITableViewDataSource` from https://github.com/Juanpe/SkeletonView/

https://github.com/Juanpe/SkeletonView/blob/2af1fd28b7b1ae635fc1c2e91e1a2a9024987706/Sources/Collections/TableViews/SkeletonTableViewProtocols.swift#L11

I was trying to use the `dataSource.forwardTo` in order to forward the methods to `SkeletonTableViewDataSource`, but looks that the binding only forwards the `UITableViewDataSource`.

Is there any way to use a subclass of `UITableViewDataSource` with bond?

Thanks

**Comment by srdanrasic** [comment]
I would suggest taking a look at Bond 7 which favours subclassing the default binder data source instead of using protocol proxies.

**Comment by eduardbosch** [comment]
Thanks @srdanrasic Works like a charm

**Comment by adelbios** [comment]
@eduardbosch We need demo example 
@srdanrasic

**Comment by eduardbosch** [comment]
@adelbios I've added an example here https://github.com/Juanpe/SkeletonView/issues/65#issuecomment-512956038
