### ISSUE TITLE
Cannot compile to staticframework

### ISSUE THREAD

**Issue by pablonosh** [DeclarativeHub/Bond#536]
Following the steps identified here:
https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md

I can't compile Bond to generate a StaticFramework.

`*** Building scheme "Differ" in Differ.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/peter/Carthage/Checkouts/Differ/Differ.xcodeproj -scheme Differ -configuration Release -derivedDataPath /Users/peter/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4_9F1027a/Differ/1.2.3 -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2x/_53hdv7j2ts7yrqbhbjbghgw0000gn/T/Differ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/peter/Carthage/Checkouts/Differ)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2x/_53hdv7j2ts7yrqbhbjbghgw0000gn/T/carthage-xcodebuild.wzz23x.log`

[carthage-xcodebuild.wzz23x.log](https://github.com/tonyarnold/Differ/files/2119769/carthage-xcodebuild.wzz23x.log)

Raised on differ github as https://github.com/tonyarnold/Differ/issues/37

**Comment by srdanrasic** [comment]
I assume this was fixed on the Differ side.
