### ISSUE TITLE
What dose skip(first:) makes?

### ISSUE THREAD

**Issue by ramunasjurgilas** [DeclarativeHub/Bond#541]
I did found that my app was not working properly when not using **skip(first:)** function. In the one of issue I found that sometimes needs to use **skip(first: 1)**. 

This function do not have clear documentation. Could someone to explain when to use **skip(first:)** and when do not use.

I know that it is not the issue, but would be nice to have response on it.

**Comment by Maxatma** [comment]
It is not clear enough what do you mean saying "my app was not working properly". 
Sometimes u have to use it skip first 'some number of' fired event. So it does exactly what its name says.

**Comment by tonyarnold** [comment]
Hi @ramunasjurgilas - as @Maxatma pointed out, `skip(first: …)` will skip the first X number of events that are sent to that signal. It is useful for avoiding initial state being overwritten, or in situations where you know you do not need the first in a sequence of events. 

If you have further questions about this method, please feel free to reopen this issue and ask them.
