### ISSUE TITLE
'TableViewBond' is deprecated: Subclass TableViewBinder instead.

### ISSUE THREAD

**Issue by edwardmp** [DeclarativeHub/Bond#546]
Hi,

Using Bond 6.8.3. this warning keeps popping up in Xcode, even though I don't use `TableViewBond` in my project.

Is there any way to fix this, or can the maintainers ship a new release where `TableViewBond` is completely removed?

Thanks!

**Comment by trevor-sonic** [comment]
Hi @edwardmp as far as I understood;
 
`TableViewBinder` is replacing `TableViewBond`

I post an example code below. But I have to say that after this implementation you will **loose** the section headers. I couldn't find the way to bring back.

`func titleForHeader` is removed in `TableViewBinder`. So something is missing. Maybe you have better understanding to find out.   


```
class TvBond: TableViewBinder<MyDataSource>, DataSourceProtocol{
    
    let viewModel = ViewModel.sharedInstance
    
    var numberOfSections: Int{
        return viewModel.array.sections.count
    }
    
    func numberOfItems(inSection section: Int) -> Int {
        return viewModel.array.numberOfItems(inSection:section)
    }
    
    override func cellForRow(at indexPath: IndexPath, tableView: UITableView, dataSource: MyDataSource) -> UITableViewCell {
        let city = viewModel.array[indexPath]
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell", for: indexPath)
        
        cell.textLabel?.text = city.name
    
        return cell
    }
}
```

And bind like;
```
viewModel.array
            .bind(to: tableView, using: TvBond())
            .dispose(in: bag)
```

**Comment by srdanrasic** [comment]
New version will be shipped in the following weeks without that warning. For now we have to keep it because of the backward compatibility.

**Comment by srdanrasic** [comment]
I was able to silence that warning before the next major version release. It should no longer be there in v6.10.
