### ISSUE TITLE
Make property of custom object Bindable

### ISSUE THREAD

**Issue by akshit-zaveri** [DeclarativeHub/Bond#554]
Basically, I want to do below
`currentPINTextField.reactive.text.bind(to: viewModel.currentPIN)`

Where `viewModel.currentPIN` is Observable and `currentPINTextField` is my custom textfield inherited from `UIView`. It has a custom text property.

How do I achieve this?

**Comment by srdanrasic** [comment]
Your custom text property has to be a signal type like Observable/Property. Then you can do `currentPINTextField.myCustomTextAsObservable.bind(to: viewModel.currentPIN)`

**Comment by akshit-zaveri** [comment]
Thanks. The TextField is in a Cocoapod. I am not able to override the property in an extension. Do you suggest something?

**Comment by srdanrasic** [comment]
Can you send me a link to that Cocoapod?
