### ISSUE TITLE
Add ability to invoke a closure for each MutableObservableArray action

### ISSUE THREAD

**Issue by npvisual** [DeclarativeHub/Bond#556]
### Context
As indicated in #555 I am trying to use MutableObservableArray (or MutableObservable2DArray) as a proxy to a backend DB. Similar to having the MutableObservableArray drive insertion, deletion, move and reload operation in a UITableView or UICollectionView, I'd like to be able to do that to the backend.

### Ideas
So far the best I have come up with was to : 

- use toPatches() to get an array of patch events
- flatMapConcat this signal to handle changes one at a time

The problem with this approach is that I don't have access to the original array for **delete operations**. Therefore I cannot replay the changes to the backend when an element is removed since backend DBs usually don't guarantee positions of elements in a collection -- and source and dataSource seem to have the same info.

Another idea is to use : 

```
array.buffer(ofSize: 2).flatMapConcat { ... }
```

to try and get the original array via `buffer(ofSize:)` and use that to retrieve the element that was removed : we should have the element(s) at the index(es) with the second item in the buffer, i.e. the last change). Seems a little kludgy...

### New feature ?
Would it make sense to have a set of closures that can be given to the MutableObservableArray for each operation -- similar to what `doOn()` does for Signals ?
Or would the best approach be to create a `SignalProtocol` extension where `bind()` is implemented for some sort of API object ?

**Comment by srdanrasic** [comment]
The set of closures does not fit well with the reactive nature of observable collections. Operator `zipPrevious` is something that could be of use here.
