### ISSUE TITLE
Realm Result to MutableObservableArray

### ISSUE THREAD

**Issue by Guferos** [DeclarativeHub/Bond#567]
I've been using Bond for the first time in my latest project and it's been fantastic experience. I am now at the point where I need to add data persistence. I am planning on using the Realm for it and wondered if anyone has managed to write an integration between Realm and MutableObservableArray that could share it here?

**Comment by Guferos** [comment]
Could not find anything online so I end up writing simple wrappers myself. 

Realm collection to ObservableRealmArray (same behaviour as ObservableArray):
[ObservableRealmArray - gist](https://gist.github.com/Guferos/bc7a852c59c09de419e450da5c2d57c1)

Realm Object to ObservableRealmObject (same behaviour as Observable):
[ObservableRealmObject - gist](https://gist.github.com/Guferos/967e1e29a9b94baa63581dae44294e87)


And you can simply use it like in the example below:
```
class User: Object {
    @objc dynamic var firstName = ""
    @objc dynamic var lastName = ""
}

let realm = try! Realm()

let users = realm.objects(User.self).sorted(byKeyPath: "firstName", ascending: true).toObservable()

users
    .bind(to: tableView, createCell: { (data, indexPath, tableView) -> UITableViewCell in
        let cellIdentifier = "Cell"
        var cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier)
        if cell == nil {
            cell = UITableViewCell(style: .subtitle, reuseIdentifier: cellIdentifier)
        }
        let user = data.item(at: indexPath.row)
        cell?.textLabel?.text = user.firstName
        cell?.detailTextLabel?.text = user.lastName
        return cell ?? UITableViewCell()
    })

let user = realm.objects(User.self).first?.toObservable()
user?.map({ $0.firstName }).bind(to: navigationItem.reactive.title)
```

It works pretty well, the only issue may arise when one will feed ObservableRealmArray with large collection from the Realm query. The Realm collections are lazy but the ObservableRealmArray loads all the data immediately therefore it may block the UI during updates. However collections must be really huge to cause any blocking, I've tested 10k records and it was still fine. To avoid any issues make sure you filter the data on the query level if you have massive collections of objects.

**Comment by Guferos** [comment]
Found a small issue with ObservableRealmObject. I didn't know that once object is deleted from the Realm db it gets invalidated and cannot be accessed anymore, therefore deletion callback needs to be handled and the value property in the ObservableRealmObject must be changed to an optional . Will try to update it today.

**Comment by Guferos** [comment]
I have updated the ObservableRealmObject to use optional for its value and the observer is handling the deleted notification now.

**Comment by srdanrasic** [comment]
That's very nice work @Guferos! It would be cool to see if performances could be improved with just released Bond 7 (beta) that refactors observable collections.

Observable collection are now properties of changeset type, for example:

```swift
typealias ObservableArray<Element> = AnyProperty<OrderedCollectionChangeset<[Element]>>
typealias MutableObservableArray<Element> = Property<OrderedCollectionChangeset<[Element]>>
```

 It feels as though observed changes from `RealmSwift.Results` could be easily mapped into `OrderedCollectionChangeset<RealmSwift.Results>` which keeps `RealmSwift.Results` type so no need to map into the array.

To enable bindings, `RealmSwift.Results` should conform to `QueryableSectionedDataSourceProtocol`.

**Comment by Guferos** [comment]
I've just test it and it works like a charm! It's great to see how easily it all mapped together and I am excited that we can keep the `Result` type so the lazy loading stays.
It's very tempting to update to the `Bond-7` now, therefore I wondered if you planning more API changes in that release or it's all about bugs fixing and performance improvements now?

**Comment by srdanrasic** [comment]
No more API changes are planned for Bond 7. I hope there are no bugs, but I still want to do more unit tests and write more documentation before it gets out of beta.

**Comment by srdanrasic** [comment]
I've made this as a Community Extension - https://github.com/DeclarativeHub/Bond/tree/master/Extensions.
