### ISSUE TITLE
Use optionals for UIButton image and backgroundImage bonds

### ISSUE THREAD

**Issue by Guferos** [DeclarativeHub/Bond#570]
Hi,

Is there any reason that UIButton `image` and `backgroundImage` bonds don't use optionals for their corresponding `Element`? I have a use case where signal bonded to the button should clear its image but unfortunately nils are not allowed. UIButton use optionals for its image and backgroundImage therefore it feels more natural to use optionals for bonds in the UIButton's `ReactiveExtension`. Unless there is good reason not to, is it possible to update UIButton extension to:
```
    ...
    @available(*, deprecated, renamed: "backgroundImage")
    public var backgroungImage: Bond<UIImage?> {
        return backgroundImage
    }

    public var backgroundImage: Bond<UIImage?> {
        return bond { $0.setBackgroundImage($1, for: .normal) }
    }

    public var image: Bond<UIImage?> {
        return bond { $0.setImage($1, for: .normal) }
    }
   ...
```
The above change should be backward compatible and does not break the API.

**Comment by srdanrasic** [comment]
This is now implemented in v7 beta 2.
