### ISSUE TITLE
Use `count` property on ObservableArray

### ISSUE THREAD

**Issue by eduardbosch** [DeclarativeHub/Bond#571]
Hi,

I've been trying to test Bond 7, but I'm having an issue with the migration.

I've seen that `MutableObservableArray` does not extend `ObservableArray` anymore. Instead, we should use `readOnlyView` to access to its non-mutable version.

The problem is that it's not possible to access `count` on an `ObservableArray` as it's possible on `MutableObservableArray`.

You can see here the problem.

```
let mutableArray = MutableObservableArray([1, 2, 3])
let nonMutableArray = a.readOnlyView

// Works great
mutableArray.count

// Error: 'AnyProperty<OrderedCollectionChangeset<[Int]>>' has no member `count`
nonMutableArray.count
```

How should we access to `count` on non-mutable properties?

Thanks

**Comment by srdanrasic** [comment]
Thanks for bringing this up @eduardbosch!

You could work around it by accessing count though the underlying collection: `nonMutableArray.collection.count`, however this was not intended issue :)

I have just released beta 2 that brings back non mutable extensions like `count`, `isEmpty` and `subscript`.

**Comment by eduardbosch** [comment]
Many thanks @srdanrasic !

I thought It was not intended. I'm glad they're back :)
