### ISSUE TITLE
NSTableView createCell closure missing

### ISSUE THREAD

**Issue by dseehof** [DeclarativeHub/Bond#573]
Hi,

any idea why I'm not able to pass the createCell closure when trying to bind a MutableObservableArray to a NSTableView? According to the documentation that should work, especially for multiple cell types.

Thanks,
Daniel

**Comment by kaishin** [comment]
I am dealing with the same problem. I believe `createCell` was removed from the API, so I opened https://github.com/DeclarativeHub/Bond/pull/576 to remove it. That said I have no further knowledge about the circumstances and of its removal nor the roadmap of the library.

**Comment by srdanrasic** [comment]
The reason is so that you can implement you own `NSTableViewDelegate`. The binding implement only `NSTableViewDataSource`.
