### ISSUE TITLE
Bidirectional Bind between UI Elements (e.g. UISwitch & UILabel) 

### ISSUE THREAD

**Issue by CelinaSkywalker** [DeclarativeHub/Bond#574]
Hello I couldn't find an example of bidirectional binding of two UI Elements, neither the information if that's possible.
my code example:
`    @IBOutlet weak var isValueSwitch: UISwitch!`
`    @IBOutlet weak var isValueLbl: UILabel!`
```
 _ = isValueSwitch.reactive.isOn.bidirectionalMap(
            to: { $0 ? "true" : "false"},
            from: { $0 == "true" })
            .bidirectionalBind(to: isValueLbl.reactive.text)
```

The Error Message is: _Argument type 'Bond<String?>' does not conform to expected type 'SignalProtocol'_

I tried it in with UILabel and UITextfield, too, but couldn't get it to work. 
Some help would be highly appreciated!

**Comment by bbaic** [comment]
@CelinaSkywalker  I want to say it's because the UILabel doesn't emit signals, as it only changes programatically. Replacing it with a UITextField (with no other changes to your code) worked in a test for me. May not _solve_ your desired use case here, but it's something...!

**Comment by srdanrasic** [comment]
The problem here was mapping into Signal<String, _> instead of into Signal<String?, _>
