### ISSUE TITLE
Replace with diff in MutableObservableArray2D

### ISSUE THREAD

**Issue by iLyaTkachev** [DeclarativeHub/Bond#578]
Could you please give an example how to make a replacement in MutableObservableArray2D with diff.
In previous version of Bond I do it in such way: 
2dArray.replace(with: Observable2DArray([section1, section2]), performDiff: true)

**Comment by srdanrasic** [comment]
Initial version of Bond v7 did not support tree/array2D diffing, but with Bond 7.1 the support is back 🎉 

The syntax remains the same, just note that you should pass the underlying collection, not the observable collection. In you case, do:

```swift
let newArray2d = Array2D<String, String>(sectionsWithItems: [
    ("Cities", ["Paris", "Berlin"])
])

mutableArray2d.replace(with: newArray2d, performDiff: true)
```
