### ISSUE TITLE
Silent Update on MutableObservableArray?

### ISSUE THREAD

**Issue by dsringari** [DeclarativeHub/Bond#583]
Hi Quick Question,

I need to silent update a specific element in an MutableObservableArray that is bound to a UITableView. The scenario is that the value represents the readStatus of that element and it needs to display as false until the UITableView reloads that UITableViewCell. The silent update would change that readStatus to true, which would hide the indicator that I am displaying on the next cellForRow.

Thanks!

**Comment by dsringari** [comment]
I resolved my specific issue by accessing the NSObject through myMutableObservableArray.collection[indexOfMyElement].readStatus = true, which worked. But how could I replace the entire object if needed?

**Comment by srdanrasic** [comment]
There is `silentUpdate` method on MutableObservableArray and other collections since Bond 7.
