### ISSUE TITLE
viewForSupplementaryElementOfKind not called when using custom binder for collection view.

### ISSUE THREAD

**Issue by Super29** [DeclarativeHub/Bond#586]
I am using CustomBinder class as given in documentation for CollectionView data source. Inside that class I have defined method for UICollectionReusableView. 

class CustomCollectionViewBinder<Changeset: SectionedDataSourceChangeset>:CollectionViewBinderDataSource<Changeset> where Changeset.Collection == Array<FileItemModel> {
    
    @objc override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(forIndexPath: indexPath) as FolderListCollectionViewCell
        return cell
    }
    
    @objc func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
        
        switch kind {
        case UICollectionElementKindSectionHeader:
            let headerView = collectionView.dequeueReusableSupplementaryView(ofKind: UICollectionElementKindSectionHeader, withReuseIdentifier: "HeaderCollectionView", for: indexPath) as! FolderHeaderCollectionReusableView
            headerView.titleLabel.text = "Headers"
            headerView.backgroundColor = UIColor.red
            return headerView
        default:
            assert(false, "Unexpected element kind")
        }
    }
}

Am I missing anything here?

**Comment by srdanrasic** [comment]
Unfortunately there is an issue in Swift compiler when dealing with ObjC delegate methods in generic subclasses. You have to manually provide ObjC method name. Check out the example in one of the playgrounds:

https://github.com/DeclarativeHub/Bond/blob/master/Playground-iOS.playground/Pages/UICollectionView%2BObservableArray2D.xcplaygroundpage/Contents.swift#L68

**Comment by Super29** [comment]
Thanks it worked for me. 👍

**Comment by diriarte2111** [comment]
Please HELP!!! Trying to do this for canEditRowAtIndexPath but I have this error "Ambiguous reference to member 'bind(signal:)"

class CustomBinder <Changeset:SectionedDataSourceChangeset>:TableViewBinderDataSource<Changeset> where Changeset.Collection == Array<MatterMember>{
    
    func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        if indexPath.row == 1 {
            return false
        }
        return true
    }
}

 members.bind(to: self.tableView1, using: CustomBinder()){array, indexPath, tableView in
            
        }
