### ISSUE TITLE
Looking up index paths of tree items

### ISSUE THREAD

**Issue by tonyarnold** [DeclarativeHub/Bond#587]
I love the look of the changes in Bond 7.1, however one limitation I've hit is that I often need to look up the index/index path of an item within the tree. 

It'd be great to have this available on the Tree, or on the relevant Binder.

**Comment by srdanrasic** [comment]
I guess this would be tree equivalent of `firstIndex(where:)`? We could add that to the Tree.

**Comment by srdanrasic** [comment]
Implemented in 7.2.0.

**Comment by tonyarnold** [comment]
Thank you!
