### ISSUE TITLE
Number Of All Elements in MutableObservableArray2D

### ISSUE THREAD

**Issue by pilmen** [DeclarativeHub/Bond#591]
Is there any easy way to get number of all elements for MutableObservableArray2D?

**Comment by bbaic** [comment]
`a2DArray.collection.children.map({ $0.count }).reduce(0, +)` is probably along the lines of what you're looking for. Yeah?

**Comment by pilmen** [comment]
Yep, that’s what I do. I thought it whould be great to add it like a property to Observable2DArray.
