### ISSUE TITLE
TreeNode move is losing index path level

### ISSUE THREAD

**Issue by tonyarnold** [DeclarativeHub/Bond#596]
https://github.com/DeclarativeHub/Bond/blob/256bb4bb2492670dd0f9957a7c0b178137b60a3a/Sources/Bond/Observable%20Collections/TreeChangeset.swift#L106

I _think_ it's coming from this method, but I'm not 100% sure. 

Given the following data structure:

```
┌───┐
│ 0 │
└───┘
  │    ┌───┐
  ├───▶│ 0 │
  │    └───┘
  │    ┌───┐
  └───▶│ 1 │
       └───┘
```

If I call move like so:

```swift
myCollection.move(from: [0, 1], to: [0, 0])
```

My custom data binder subclass receives the following operation via the `applyOperation` method:

```swift
.move(from: [0, 1], to: [0])
```

There appears to be a separate move that comes after this, but I can't get to that data in LLDB at the moment.

This doesn't seem right, but I'm having trouble finding the point where it's falling apart (I actually assume it's within `generatePatch(…)`).

Any thoughts? I'm happy to fix it, if you can point me in the right direction.

**Comment by srdanrasic** [comment]
Hmm, 2-level index paths are invalid for the tree in your example. For example, index path `[]` refers to the root node, index path `[1]` refers to the second child of the root node, while index path `[1, 2]` refers to the third child of the second child of the root node.

Following works correctly for me:

```swift
var t = TreeNode("Child 00", [
    TreeNode("Child 000"),
    TreeNode("Child 001"),
])

let ot = MutableObservableTree(t)

ot.observeNext { (cs) in
    print(cs.collection, cs.diff, cs.patch)
}

ot.move(from: [1], to: [0])
```

When I do `ot.move(from: [0, 1], to: [0, 0])`, it crashed as expected.

**Comment by tonyarnold** [comment]
```
┌───┐
│ 0 │
└───┘
  │    ┌───┐
  ├───▶│ 0 │
  │    └───┘
  │    ┌───┐
  └───▶│ 1 │
       └───┘
┌───┐
│ 1 │
└───┘
  │    ┌───┐
  ├───▶│ 0 │
  │    └───┘
  │    ┌───┐
  └───▶│ 1 │
       └───┘
```

Right, but in this situation (which is what I have), wouldn't a move from [0, 1] to [0, 0] be valid?

**Comment by srdanrasic** [comment]
That would be valid, sure. I can't reproduce you issue though:

```swift
var t = TreeArray([
    TreeNode("Child 0", [
        TreeNode("Child 00"),
        TreeNode("Child 01")
    ]),
    TreeNode("Child 1", [
        TreeNode("Child 10"),
        TreeNode("Child 11")
    ])
])

let ot = MutableObservableTree(t)

ot.observeNext { (cs) in
    print(cs.collection, cs.diff, cs.patch)
}

ot.move(from: [0, 1], to: [0, 0])
```

correctly gives me:

```
[(Child 0: (Child 01: -), (Child 00: -)), (Child 1: (Child 10: -), (Child 11: -))] Inserts: [], Deletes: [], Updates: [], Moves: [(from: [0, 1], to: [0, 0])] [M(from: [0, 1], to: [0, 0])]
```

**Comment by tonyarnold** [comment]
Yeah, this seems to be an issue in my implementation. Sorry for taking up time on it!
