### ISSUE TITLE
Generic parameter 'B' could not be inferred

### ISSUE THREAD

**Issue by PKCoder2020** [DeclarativeHub/Bond#598]
var emailID = Observable<String>("")
    @IBOutlet weak var texfField: UITextField!

        emailID.bidirectionalBind(to: texfField.reactive.text) throws compilation error "Generic parameter 'B' could not be inferred"

**Comment by srdanrasic** [comment]
`text` on the text field is an optional string, so your observable also needs to be optional string in order for the bidirectional binding to work.

```swift
var emailID = Observable<String?>("")
```

**Comment by Maxatma** [comment]
@srdanrasic could be nice to have this in readme :)
