### ISSUE TITLE
combination publish subject and property using merge

### ISSUE THREAD

**Issue by Maxatma** [DeclarativeHub/Bond#599]
`Cannot invoke 'merge(_:_:_:)' with an argument list of type '(SafePublishSubject<Void>, SafePublishSubject<Void>, Property<String>)'
`

`            merge(pbsubj1, pbsubj2, observableProperty)
`
Can this:
`merge(pbsubj1, pbsubj2)
`
Can this

`merge(observableProperty, observableProperty)
`
But can't combine them somewhy

How to do that? is it a bug? 
Simple usercase, when i want to combine 2 different refreshes and textfield change to invoke server request.

**Comment by Maxatma** [comment]
Seems like 
```
    let stringSubject = SafePublishSubject<String>()
    let voidSubject = SafePublishSubject<Void>()
```

are also impossible to combine.
Is it expected behaviour?

**Comment by srdanrasic** [comment]
Yes, you cannot merge signals of different types. What would the resulting signal type be? String or Void?

You can solve this by mapping signals to the same type, Void in your case:

```swift
merge(pbsubj1, pbsubj2, observableProperty.map { _ in })
```

**Comment by Maxatma** [comment]
@srdanrasic It's simple, I want to get 3 types of evens independently , 2 of them just make request, 3rd makes request with value in produced. 

I can't use combineLatest, coz i want them to work independently. 
See the difference between merge and combineLatest:
https://rxmarbles.com/

**Comment by srdanrasic** [comment]
`merge` and `combineLatest` work exactly as they are depicted on RxMarbles. You can see there that they are also using the same type in the merge example (Int) and the different types in combine example (Int + String).

It see you problem. I think it still boils down to choosing the right type. You could map all signals into `String?` and then make different request based on whether it's nil or not.

```swift
let requestIntent = merge(
    pbsubj1.map { String?.none },
    pbsubj2.map { String?.none },
    observableProperty.map { String?.some($0) }
)
```

You could introduce a custom type and map it into that if you want to be more descriptive.

```swift
enum RequestIntent {
    case refresh
    case reload(String)
}
```

**Comment by Maxatma** [comment]
@srdanrasic oh, i see, it work exaclty like on marbles. 
Sure i can use some workaround code to achieve my needs, but I dont understand why two similar operators work so differently: there is not only difference that they produce events in different manner (merge in any of observed  event, combineLatest in case all appears first and the on every next even)   , but they first produce _,_,_ and merge only _

I think should exist merge analog which produce every value _,_,_ on any event.

**Comment by srdanrasic** [comment]
The provided operators cover most of the use cases. Hope you have found a solution for your specific use case. I'll close the issue.
