### ISSUE TITLE
Generating patch from diff - possible bug?

### ISSUE THREAD

**Issue by akospalfi** [DeclarativeHub/Bond#600]
Hello everyone,

I'm working on an bindable "datasource" implementation for NSPopUpButton and I found a really interesting behaviour when I try to generate a patch from a diff:

```swift
let testArr = ["Apple", "Pear", "Banana"]

var diff = OrderedCollectionDiff<Int>()

diff.inserts.append(0)
diff.inserts.append(1)
diff.inserts.append(2)

var changeset = OrderedCollectionChangeset(collection: testArr, diff: diff)

print(changeset.diff)
print("Generated patch:")
print(changeset.patch)
```
Output:
```
Inserts: [0, 1, 2], Deletes: [], Updates: [], Moves: []
Generated patch:
[I(Apple, at: 0), I(Pear, at: 1), I(Banana, at: 2)]
```

Here it seems everything is correct, the generated patch is correct.

But if I organize the indexes to a non-increasing order:
```swift
let testArr = ["Apple", "Pear", "Banana"]

var diff = OrderedCollectionDiff<Int>()

diff.inserts.append(0)
diff.inserts.append(2)
diff.inserts.append(1)

var changeset = OrderedCollectionChangeset(collection: testArr, diff: diff)

print(changeset.diff)
print("Generated patch:")
print(changeset.patch)
```
Output:
```
Inserts: [0, 2, 1], Deletes: [], Updates: [], Moves: []
Generated patch:
[I(Apple, at: 0), I(Banana, at: 1), I(Pear, at: 1)]
```
In this case, shouldn't the patch be `[I(Apple, at: 0), I(Banana, at: 2), I(Pear, at: 1)]` ?

Thanks,
Akos

**Comment by srdanrasic** [comment]
Hi Akos,

For a single diff, there can be multiple valid patches. Both first and second patch are correct. You can check that if you try to apply the operations.

1st example:

Step|Array
---|---
Inital | []
I(Apple, at: 0) | [Apple]
I(Pear, at: 1) | [Apple, Pear]
I(Banana, at: 2) | [Apple, Pear, Banana]

2nd example:

Step|Array
---|---
Inital | []
I(Apple, at: 0) | [Apple]
I(Banana, at: 1) | [Apple, Banana]
I(Pear, at: 1) | [Apple, Pear, Banana]

As you can see, in both cases we end up with the correct array. If we were to try your example, this would happen:

Step|Array
---|---
Inital | []
I(Apple, at: 0) | [Apple]
I(Banana, at: 2) | Fatal error (index out of bounds)
... | ...

We cannot insert at index 2 if the array size is 1.

There are more possible valid patches for the same diff, for example this one:

Step|Array
---|---
Inital | []
I(Banana, at: 0) | [Banana]
I(Pear, at: 0) | [Pear, Banana]
I(Apple, at: 0) | [Apple, Pear, Banana]

Now, the reason we are getting different patches from the same, but differently sorted, diff is that the algorithm that generates it is not stable. The order of diff indices will cause the algorithm to take different paths and produce different results. The result is still correct, we are just taking the most efficient way to generate it.

If you need a stable patch generation, then you'll need to sort diff indices before getting the patch.

**Comment by akospalfi** [comment]
Oh, now everything makes total sense! Thank you so much for the detailed explanation Srdan!

Now I see that the problem was of course in my own code, but I was testing with a very complicated dataset, and I wasn’t able to figure out from the logs why the indices are so ‘weird’, but now I was able to solve the puzzle. :)
