### ISSUE TITLE
Scroll the tableview to last IndexPath on every on next event after binding 

### ISSUE THREAD

**Issue by ibrahimkteish** [DeclarativeHub/Bond#603]
I was wondering what is the best way to make `UITableView` scroll to last `IndexPath` on every data change

I am using the simplest way to populate the data like the following:
```swift 
 self.items.bind(to: self.tableView, cellType: AnyTableViewCell.self) { (cell, item) in

      //setup cell here using item
      
    }
```

**Comment by srdanrasic** [comment]
You could subclass the table view and override `reloadData`, `insertRows`, etc, by doing the scroll after calling the super implementation. 

Alternatively you can implement a [custom binder](https://github.com/DeclarativeHub/Bond/blob/master/Documentation/DataSourceSignals.md#advanced-bindings-custom-binder-data-sources) by subclassing the default one [TableViewBinderDataSource](https://github.com/DeclarativeHub/Bond/blob/master/Sources/Bond/UIKit/UITableView%2BDataSource.swift#L212) and overriding `applyChangeset` and/or `applyChangesetDiff`.

**Comment by ibrahimkteish** [comment]
Thank you so much @srdanrasic
