### ISSUE TITLE
Initialize Array2D Section with custom classes

### ISSUE THREAD

**Issue by lindseypisaak** [DeclarativeHub/Bond#605]
I just updated my Bond pod from 6.8.3 to 7.3.0, and went from Swift 4 to Swift 4.2, and I'm running into some issues converting the new 2D array stuff. In my existing code, initializing a 2D array section like this worked fine:
`Observable2DArraySection<HeaderViewModel, ItemsProtocol>(metadata: HeaderViewModel(text: "Header"), items: [ConcreteItemClass()])`

Now, I'm unsure how to initialize a Section for Array2D. I assume that this should work, but it always gives the error "Type of expression is ambiguous without more context."
`Array2D<HeaderViewModel, ItemsProtocol>.Section(metadata: HeaderViewModel(text: "Header"), items: [ConcreteItemClass()])`

Any help would be greatly appreciated. I can initialize a Section with primitive types just fine, but any time I try to use custom classes instead, it gets an error.

**Comment by srdanrasic** [comment]
Oops, looks like `Array2D.Section` initializer was not public. I've just released 7.3.1 with the fix. (CocoaPods build coming any minute)

You seem to be doing everything correctly. Let me know if you stumble upon any other issue.

**Comment by lindseypisaak** [comment]
Thank you!! All good now, and good to know I wasn't losing my mind. Appreciate the quick help.
