### ISSUE TITLE
Replace section in Array2D

### ISSUE THREAD

**Issue by lindseypisaak** [DeclarativeHub/Bond#606]
MutableObservable2DArray had the ability to replace an entire section and notify observers (Issue #338). I can't seem to find the equivalent for Array2D. Was it removed, or is there a new alternative that I'm missing?

**Comment by srdanrasic** [comment]
Looks like this is something we forgot in Bond 7, but no worries, I've just brought it back in 7.3.3: https://github.com/DeclarativeHub/Bond/releases
