### ISSUE TITLE
canEditRowAt delegate not firing

### ISSUE THREAD

**Issue by lindseypisaak** [DeclarativeHub/Bond#611]
Since updating to 7.3, the canEditRowAt delegate never seems to fire (in my case, I have my tableView bound to a MutableObservableArray2D). My leading and trailing swipe actions work just fine, but I'm no longer able to control when to hide/show them.

**Comment by srdanrasic** [comment]
What version did you update from?

**Comment by lindseypisaak** [comment]
Sorry, 6.8.3

**Comment by srdanrasic** [comment]
Could you post a piece of code that shows how you set up the delegate? 

I'd also recommend that you clone Bond repo and check out the playgrounds in the workspace, they explain how to setup delegates in Bond 7.

**Comment by lindseypisaak** [comment]
I don't see anything in the iOS playground that references delegates? It's mostly just modifying the data in an array and observing. Right now all we do to setup the tableView delegate is this
`self.tableView.reactive.dataSource.forwardTo = self
 self.tableView.reactive.delegate.forwardTo = self`

**Comment by srdanrasic** [comment]
Ah, unfortunately this is not supported any more because the binding data source sets itself as `forwardTo`. To implement additional data source methods like `canEditRowAt`, please subclass the default binder as explained in `UICollectionView+ObservableArray2D` playground.

**Comment by lindseypisaak** [comment]
Ah okay, thanks. Sorry for tacking on a question to this, but does the cell type in bind(to:cellType:using) have to be a concrete class? We use protocols for quite a few of our cell types, but trying to use the protocol as the cell type results in an ambiguous declaration error.

**Comment by srdanrasic** [comment]
Not sure how that would work because in the end somebody must instantiate the concrete class. 

Maybe you could make you own extension method on `SignalProtocol` that takes in custom binding parameters, make a binder from that and then calls `bind(to:using:)`? Check out how Bond implements one of `bind(to:)` overloads: https://github.com/DeclarativeHub/Bond/blob/master/Sources/Bond/UIKit/UITableView%2BDataSource.swift#L41
