### ISSUE TITLE
Xcode 10.2 breaking on MutableObservableArray.batchUpdate

### ISSUE THREAD

**Issue by ZaBlanc** [DeclarativeHub/Bond#615]
I'm still trying to get a stack trace, but I'm getting crashes on batchUpdate in Xcode 10.2. Everything was fine in 10.1 but in order to build for iOS 12.2 I had to upgrade Xcode and now the app crashes on the batchUpdate call.

Anyone seeing anything similar? I will update this once I get a stack trace...not sure why I can't.

**Comment by srdanrasic** [comment]
It would be great if you could get us more details on this. Also on the Bond version you are using.

**Comment by srdanrasic** [comment]
I'll close this since there is no additional information. If you get us more details, feel free to reopen the issue.
