### ISSUE TITLE
6.10.2 does not compile

### ISSUE THREAD

**Issue by Guferos** [DeclarativeHub/Bond#617]
Hi,

I've just run pod update which updated the Bond from 6.10.2 to 6.10.4 (I am running version 6 in my project) on top of that ReactiveKit version got updated from 3.9.7 to 3.10.0.

After the update I cannot build the project anymore as it fails with a number of different errors when building ReactiveKit module. (see below) 

![errors screenshot](https://i.ibb.co/8dYDj0V/Screenshot-2019-04-02-at-12-50-43.png)

Have there been any significant changes to the ReactiveKit 3.10.0 ? Is there any way to downgrade it back to 3.9.7?

**Comment by srdanrasic** [comment]
Bond 6.10.2 and ReactiveKit 3.9.7 are the latest versions that work with earlier versions of Swift. Until you update to Xcode 10.2, you can pin the Cartfile to:

github "DeclarativeHub/Bond" == 6.10.2
github "DeclarativeHub/ReactiveKit" == 3.9.7

**Comment by Guferos** [comment]
Thanks for the reply. I end up forking the Bond and updating the spec file to use ReactiveKit 3.9.7 for Bond-6.
