### ISSUE TITLE
Differ Version not updated in Podspec

### ISSUE THREAD

**Issue by mbhuta** [DeclarativeHub/Bond#618]
Hi, I noticed that the Differ dependency version has not been updated in the Podspec file - it is still at 1.3, as compared to the Package file where it has been bumped to 1.4. When I run a pod update, Bond and ReactiveKit get updated, but the Differ version remains at 1.3 which generates a bunch of redundant 'public' keyword warnings in Xcode 10.2. I am new to cocoapods, so am I doing something incorrectly, or does the podspec need to be updated?

**Comment by srdanrasic** [comment]
You seem to be doing everything correctly and you can ignore the warnings. They will be gone when we get @tonyarnold to do `pod trunk push` :)

**Comment by mbhuta** [comment]
Ah I see. Thank you!

**Comment by tonyarnold** [comment]
Whoops! 

Righto, all pushed and ready to go 🎉

**Comment by mbhuta** [comment]
@tonyarnold Thanks so much! All warnings resolved :) And thanks again @srdanrasic
