### ISSUE TITLE
bind(to: ) causes a crash after updating Bond

### ISSUE THREAD

**Issue by mbhuta** [DeclarativeHub/Bond#619]
Previously I was using Bond version 7.3.3, and everything was working just fine when I set up my viewModel bindings, but now for some reason after updating Bond via pod update, the app crashes when I call the bind method. Here is the code snippet causing the crash -

`self.viewModel?.currentTool.map { $0 == nil ? false : true }.bind(to: self.reactive.isHidden)`

Am I missing something?

**Comment by srdanrasic** [comment]
I don’t see anything that should crash on that line. Could you share some more details like the stack trace?

**Comment by mbhuta** [comment]
Sure - 
<img width="312" alt="Screen Shot 2019-04-02 at 6 20 02 PM" src="https://user-images.githubusercontent.com/2553839/55403672-fca85100-5573-11e9-9c59-f2459ceaf6bd.png">

**Comment by mbhuta** [comment]
I am basically using a propertyobserver 'didSet' for when the viewModel is set for the view, and setting up bindings there

**Comment by srdanrasic** [comment]
`dyld_stub_binder` indicates some linking issues. Could be something with CocoaPods. I'd also try deleting derived data if you haven't tried that already.

**Comment by mbhuta** [comment]
Perfect! Deleting derived data worked :)
