### ISSUE TITLE
Swift Compile Errors for old Bond versions because ReactiveKit Swift 5 update

### ISSUE THREAD

**Issue by ISCHI** [DeclarativeHub/Bond#620]
We have a project which uses Bond version 6.8.3 (pinned in Podfile), Swift 4.2 and Xcode 10.1.
Today the build server failed with many compile errors because of ReactiveKit. Very strange, because we don't have made any changes in our project....

The problem is, that the version of ReactiveKit in Bond.podspec is only pinned to `~> 3.9`. Some days ago, ReactiveKit released version 3.10 with Swift 5. Now old Bond versions doesn't work anymore (out of the box).

Output from pod install:
```bundle exec pod install
Analyzing dependencies
Downloading dependencies
Installing Bond (6.8.3)
Installing Differ (1.3.0)
Installing ReactiveKit (3.10.0)
...
```

### Quick solution
A quick solution is to pin the ReactiveKit version in the projects Podfile.
Now out Podfile looks like this:
```platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings! 

def app_pods
    pod 'Bond', '6.8.3'
    pod 'ReactiveKit', '3.9.6' # version ist not pinned by Bond.podspec
end
````
For the future it may be better to pin a fix version of ReactiveKit (at least major and minor)... ?

**Comment by srdanrasic** [comment]
Thanks for reporting this @ISCHI. I see the problem it caused. We will try to be more cautious in future. Glad you have resolved it!
