### ISSUE TITLE
MutableObservableArray2D diff

### ISSUE THREAD

**Issue by omerCoosto** [DeclarativeHub/Bond#624]
hello guys!

I'd like to know if it's made on purpose that when i add a Section with an empty items array into a **MutableObservableArray2D** an event is sent to ObserveNext with an **IndexPath [0, 0]**.

In my case that make the app crash as there is no item to insert at [0, 0] on the tableView (it should crash also when updating/deleting an empty section with the following example)

I can do a workaround by checking if the section is empty before insertion of course but i was just worried if it should work like this or not?

Thanks, here the example:

```
// viewModel
let dummySection = [("A", [])]
self.datas.appendSection(dummySection)


// viewController

 _ = viewModel.datas.observeNext(with: { [weak self] changes in
            guard let safeSelf = self else { return }
            let inserts = changes.diff.inserts
            let deletes = changes.diff.deletes
            let updates = changes.diff.updates

            if !inserts.isEmpty { safeSelf.contentTableView?.insertRows(at: inserts, with: .automatic) }
            if !deletes.isEmpty { safeSelf.contentTableView?.deleteRows(at: deletes, with: .automatic) }
            if !updates.isEmpty { safeSelf.contentTableView?.reloadRows(at: updates, with: .automatic) }
        })

```

**Comment by omerCoosto** [comment]
I find the solution to my question :) 
Was actually a single index in the IndexPath to notify that it's the section which get updated not the items. I was not use to use IndexPath it like this.

I put the "fix" here.

```
            let inserts = changes.diff.inserts.filter({ $0.count > 1 })
            let deletes = changes.diff.deletes.filter({ $0.count > 1 })
            let updates = changes.diff.updates.filter({ $0.count > 1 })
```

You can close this issue :)

**Comment by srdanrasic** [comment]
Single element index paths give you information about section changes. Glad that you have figured it out.
