### ISSUE TITLE
How to update an item in MutableObservableArray2D

### ISSUE THREAD

**Issue by omerCoosto** [DeclarativeHub/Bond#625]
Hi,

I'm trying to update an item in a section.
So i have a MutableObservableArray2D like in the following example:
```
// 2D Array

struct Person {
   var name: String
   var age: Int
}

let array2D = MutableObservableArray2D(Array2D<String, String>(sectionsWithItems: [
    ("Author", [Person("Mike", 18), Person("john", 25)]), ...
]))

```

what i'm trying to do is the same as with a simple MutableObservableArray, which mean changing a value in an object of my items (like in following example), which will send a observable notification.

```
// 1D Array

let array = MutableObservableArray([Person("Mike", 18), Person("john", 25)])
array[0].name = "Kevin"
```

So on my MutableObservableArray2D i tried: 
```
datas.collection.sections[0].items[0].name = "Kevin"
// OR
datas.tree.sections[0].items[0].name = "Kevin"

```
but i get this message: 

> Cannot use mutating member on immutable value: 'collection' is a get-only property

In the documentation it explain how to append but nothing about a simple object update like this.
https://github.com/DeclarativeHub/Bond/blob/master/Documentation/ObservableCollections.md

I must have miss something because it's simple what i need :D, thanks for your help!

**Comment by janiduw** [comment]
I'm struggling with the same issue. Would be great to have some help. Thank you!

**Comment by srdanrasic** [comment]
To access or mutate an item at the given index path, you can do:

```swift
data[itemAt: [0, 0]].name = "Kevin"
```

Note that `[0, 0]` is an index path. It can also be expressed as `IndexPath(item: 0, section: 0)`.

Likewise, to access or mutate a whole section at the given index, you can do:

```swift
data[sectionAt: 0] = .init(metadata: "People", items: [Person(name: "Kevin", age: 20)])
```

Hope this helps.

**Comment by janiduw** [comment]
Thank you ! that really helped :)

**Comment by omerCoosto** [comment]
Thank you for the explanation! 
Will be nice to have it in the [Documentation](https://github.com/DeclarativeHub/Bond/blob/master/Documentation/ObservableCollections.md#observable2darray--mutableobservable2darray) 👍 
(you can close this ticket :) )
