### ISSUE TITLE
Question: How to filter elements in MutableObservableArray2D?

### ISSUE THREAD

**Issue by druvv** [DeclarativeHub/Bond#640]
Hello running on Bond 7 here.

How do I filter elements from a MutableObservableArray2D?

I have a sectioned list of items in a tableview and I need to add search functionality that filters each of the sections by the search text.

I don't understand how to use the .filter() method because it returns a TreeChangeset, could someone explain?

Thank you!

**Comment by jagsrajput21** [comment]
@dsringari I am also having the same issue. Have you found any solutions ?

**Comment by CelinaSkywalker** [comment]
I have the same question

**Comment by someyura** [comment]
If anyone is still looking for an answer, here is how I solved this problem.

```
// let's say you have an observable two-dimentional array
let array2D = MutableObservableArray2D(...)

// you can get a two-dimentional array of its items like this
let sections = array2D.collection.children.compactMap({ $0.section?.items })

// then you can turn it into a regular array
let allItems = Array(sections.joined())

// and filter
let filteredItems = allItems.filter({ /* your filtering logic here */ })
```
