### ISSUE TITLE
one-to-many binding (syntax)

### ISSUE THREAD

**Issue by richardtop** [DeclarativeHub/Bond#644]
Hi, I'm interested in binding a single Observable<Bool> to multiple receivers.
How can I achieve this concisely?

Currently, I have to resort to binding every property:

```Swift
model.sectionEnabled.map{!$0}.bind(to: vc1.view.reactive.isHidden)
model.sectionEnabled.map{!$0}.bind(to: vc2.view.reactive.isHidden)
model.sectionEnabled.map{!$0}.bind(to: vc3.view.reactive.isHidden)
....
```

What if it would be possible to use the following construct?:
```Swift
model.sectionEnabled.map{!$0}
.bind(to: vc1.view.reactive.isHidden)
.bind(to: vc2.view.reactive.isHidden)
.bind(to: vc3.view.reactive.isHidden)
.bind(to:.......
```
Is it already possible to do such binding with the current implementation of the framework?

**Comment by srdanrasic** [comment]
There is not built in way to do one to many binding, but maybe you could do something like:

```swift
let sectionEnabled = model.sectionEnabled.map{!$0}
[vc1.view, vc2.view, vc3.view].forEach { sectionEnabled.bind(to: $0.reactive.isHidden) }
```

**Comment by richardtop** [comment]
Thanks. Before "forEach" step it's possible to add an additional "map" to extract views.
