### ISSUE TITLE
Project file uses SRCROOT; should be PROJECT_DIR

### ISSUE THREAD

**Issue by deborahgoldsmith** [DeclarativeHub/Bond#690]
The project.pbxproj file currently uses the symbol SRCROOT to refer to various locations in the project source. This does not work in certain build situations, where SRCROOT may point at the root of a larger project which includes this one as a submodule.

The correct symbol to use is PROJECT_DIR. This works the same for standalone builds, and also works when Bond is a submodule of another project.

I have a patch which I will put into a pull request shortly.

**Comment by deborahgoldsmith** [comment]
PR is #691

**Comment by srdanrasic** [comment]
Thanks @deborahgoldsmith, the PR is merged.
